; 'use strict';
var Hooks=Hooks||{};
Hooks.actions=Hooks.actions||{};
Hooks.filters=Hooks.filters||{};
Hooks.add_action = function(tag,callback,priority){if(typeof priority==="undefined"){priority=10};Hooks.actions[tag]=Hooks.actions[tag]||[];Hooks.actions[tag].push({priority:priority,callback:callback})};
Hooks.add_filter = function(tag,callback,priority){if(typeof priority==="undefined"){priority=10};Hooks.filters[tag]=Hooks.filters[tag]||[];Hooks.filters[tag].push({priority:priority,callback:callback})};
Hooks.remove_action = function(tag,callback){Hooks.actions[tag]=Hooks.actions[tag]||[];Hooks.actions[tag].forEach(function(filter,i){if(filter.callback===callback){Hooks.actions[tag].splice(i,1)}})};
Hooks.remove_filter = function(tag,callback){Hooks.filters[tag]=Hooks.filters[tag]||[];Hooks.filters[tag].forEach(function(filter,i){if(filter.callback===callback){Hooks.filters[tag].splice(i,1)}})};
Hooks.do_action = function(tag,options){var actions=[];if(typeof Hooks.actions[tag]!=="undefined"&&Hooks.actions[tag].length>0){Hooks.actions[tag].forEach(function(hook){actions[hook.priority]=actions[hook.priority]||[];actions[hook.priority].push(hook.callback)});actions.forEach(function(hooks){hooks.forEach(function(callback){callback(options)})})}};
Hooks.apply_filters = function(tag,value,options){var filters=[];if(typeof Hooks.filters[tag]!=="undefined"&&Hooks.filters[tag].length>0){Hooks.filters[tag].forEach(function(hook){filters[hook.priority]=filters[hook.priority]||[];filters[hook.priority].push(hook.callback)});filters.forEach(function(hooks){hooks.forEach(function(callback){value=callback(value,options)})})};return value};